# -*- coding: utf-8 -*-
"""Amazon Sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152OZNeKz08R57gxALB_d9Nlu0DRknq8K
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
amazon_df = pd.read_csv('/content/sample_data/amazon.csv.zip')

# Data Cleaning
# Removing the currency symbol and commas in `discounted_price`, `actual_price`, and converting them to numeric
amazon_df['discounted_price'] = amazon_df['discounted_price'].replace('[₹,]', '', regex=True).astype(float)
amazon_df['actual_price'] = amazon_df['actual_price'].replace('[₹,]', '', regex=True).astype(float)
amazon_df['discount_percentage'] = amazon_df['discount_percentage'].replace('%', '', regex=True).astype(float)

# Convert `rating_count` to numeric after removing commas
# Replace NaN values with 0 before converting to integer
amazon_df['rating_count'] = amazon_df['rating_count'].replace(',', '', regex=True)
amazon_df['rating_count'] = pd.to_numeric(amazon_df['rating_count'], errors='coerce').fillna(0).astype(int)

# Basic Analysis
print(amazon_df.describe())

# Plotting Distribution of Ratings
plt.figure(figsize=(10, 6))
sns.histplot(amazon_df['rating'], bins=10, kde=True)
plt.title("Distribution of Product Ratings")
plt.xlabel("Rating")
plt.ylabel("Frequency")
plt.show()

# Distribution of Discount Percentage
plt.figure(figsize=(10, 6))
sns.histplot(amazon_df['discount_percentage'], bins=20, kde=True)
plt.title("Distribution of Discount Percentage")
plt.xlabel("Discount Percentage")
plt.ylabel("Frequency")
plt.show()

# Average Discounted Price by Category
avg_discounted_price = amazon_df.groupby('category')['discounted_price'].mean().sort_values(ascending=False)
plt.figure(figsize=(12, 8))
avg_discounted_price.plot(kind='bar')
plt.title("Average Discounted Price by Category")
plt.xlabel("Category")
plt.ylabel("Average Discounted Price")
plt.xticks(rotation=90)
plt.show()

# Top 10 Most Reviewed Products
top_reviewed_products = amazon_df.sort_values(by='rating_count', ascending=False).head(10)
plt.figure(figsize=(12, 6))
sns.barplot(data=top_reviewed_products, x='product_name', y='rating_count')
plt.title("Top 10 Most Reviewed Products")
plt.xlabel("Product Name")
plt.ylabel("Review Count")
plt.xticks(rotation=90)
plt.show()